version: "3"
virtualmachines:
- name: docker-vm
  #image: instruqt-sean/k3s-latest-27deb8f3-aa77-45ea-9892-4e201fb269c7
  image: instruqt/docker-2010
  shell: /bin/bash
  machine_type: n1-standard-2
  allow_external_ingress:
  - high-ports
