#!/bin/bash 

set -euxo pipefail

# Wait for the Instruqt host bootstrap to finish
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done

# # Wait for the Kubernetes API server to become available
while ! curl --silent --fail --output /dev/null http://localhost:8001/api 
do
    sleep 1 
done

apt-get update

# # Enable bash completion for kubectl
curl https://raw.githubusercontent.com/ahmetb/kubectl-aliases/master/.kubectl_aliases -o /root/.kubectl_aliases

printf "source /usr/share/bash-completion/bash_completion\ncomplete -F __start_kubectl k\nexport do=('--dry-run=client' '-o' 'yaml')\n[ -f ~/.kubectl_aliases ] && source ~/.kubectl_aliases\n" >> /root/.bashrc

## direnv
apt install direnv
direnv --version
echo 'eval "$(direnv hook bash)"' >> /root/.bashrc

# crane
go install github.com/google/go-containerregistry/cmd/crane@latest

# Docker CE
curl -fsSL https://get.docker.com -o get-docker.sh
sh ./get-docker.sh

systemctl enable docker
systemctl start docker

rm -f get-docker.sh

## envsubst
envsubst --version

# httpie
# apt install -y httpie
snap install httpie

# kustomize
snap install kustomize

# kubens + kubectx
snap install --classic kubectx

# jq
snap install jq

# starship
snap install starship

echo 'eval "$(starship init bash)"' >> /root/.bashrc

# yq
snap install yq

## Extract all examples here
mkdir -p "$HOME/repos"
echo 'export GIT_REPOS_HOME="$HOME/repos"' >> /root/.bashrc
echo 'export TUTORIAL_HOME=/root/repos/drone-ci-101' >> /root/.bashrc

cd "$HOME/repos" || true
git clone https://github.com/harness-apps/drone-ci-101.git drone-ci-101

set-workdir "$PWD"
