#!/usr/bin/env bash
eval "$(direnv export bash)"

set -euxo pipefail

direnv allow .

kubectl rollout status deployment -n drone drone --timeout=60s || fail-message "I expected a drone deployment"

kubectl rollout status deployment -n drone drone-runner-docker --timeout=60s || fail-message "I expected a drone-runner-docker deployment"

exit 0
