#!/usr/bin/env bash
eval "$(direnv export bash)"

set -euxo pipefail

container_id=$(docker ps --filter name=registry --format="{{ .ID }}")

[[ -n "$container_id" ]] || fail-message "Expected to have a container registry running"

# Docker push
(docker pull gcr.io/google-samples/hello-app:1.0;docker tag gcr.io/google-samples/hello-app:1.0 "localhost:5001/hello-app:1.0";docker push "localhost:5001/hello-app:1.0") || fail-message "Unable to push image to the private registry"

# Kubectl
(kubectl create deployment hello-server --image="my-registry.localhost:5001/hello-app:1.0";
kubectl rollout status deployment.apps/hello-server --timeout=30s) || fail-message "I expect the application deployment to succeed"


kubectl delete deployment.apps/hello-server